name: Unit Tests / PHP (v7.4.1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.1'
        tools: phpunit
      
    - name: Run test suite
      run: composer run-script tests

    - name: Check PHP version
      run: php -v

