name: Unit Tests / PHP (v7.4.1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MYSQL_GITHUB_ACTION: true
      MYSQL_DATABASE: stackable
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root


    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_DATABASE: ${{ MYSQL_DATABASE }}
          MYSQL_USER: ${{ MYSQL_USER }}
          MYSQL_PASSWORD: ${{ MYSQL_USER }}
          MYSQL_ROOT_PASSWORD: ${{ MYSQL_ROOT_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.1'
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test

    - name: Check PHP version
      run: php -v

