name: Unit Tests / PHP (v7.4.1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_DATABASE: stackable
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4.1'
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run MYSQL server
      run: |
        sudo systemctl enable mysql.service
        sudo systemctl start mysql.service
        sudo /etc/init.d/mysql start
        sudo /etc/init.d/mysql -u root -proot -h 127.0.0.1 -e 'CREATE DATABASE stackable'

    - name: Run test suite
      env:
        MYSQL_GITHUB_ACTION: true
        MYSQL_DATABASE: stackable
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}

      run: composer run-script test

    - name: Check PHP version
      run: php -v

