name: Unit Tests / PHP (v8.0.0)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'stackable' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql version: '5.6'
        mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'root' # Required if "mysql user" exists. The password for the "mysql user"

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password=root --silent; do
          sleep 1
        done
    - name: Setup PHP v8.0.0
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0.0'

    - name: Check PHP version
      run: php -v
      
    - name: Install dependencies
      run: |
        composer require phpunit/phpunit:7.0.0 --dev --ignore-platform-reqs
        composer install --prefer-dist --no-progress --ignore-platform-reqs

    - name: Run test suite
      env:
        MYSQL_GITHUB_ACTION: true
        MYSQL_DATABASE: stackable
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PORT: 3306
      run: composer run-script test
