name: Unit Tests / PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['5.6.39', '7.3.5', '7.4.1', '8.0.0']


    steps:
    - uses: actions/checkout@v2

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'stackable' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'root' # Required if "mysql user" exists. The password for the "mysql user"

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check PHP version
      run: php -v

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      env:
        MYSQL_GITHUB_ACTION: true
        MYSQL_DATABASE: stackable
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PORT: 3306

      run: composer run-script test


