name: Test

on:
  repository_dispatch:
    types: [start-example-workflow]

jobs:
  start-example-workflow:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
        
    - name: Build Stackable Free Plugin
      run: |
        echo ${{ github.event.client_paayload.sample_key }}